# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'StringifyExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StringifyExample
  pod 'Extendy', '1.1'
end
